# Generated by Django 2.1.2 on 2019-04-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaagenda', models.DateTimeField()),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nomcargo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('runcliente', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=80)),
                ('apepaterno', models.CharField(max_length=80)),
                ('apematerno', models.CharField(max_length=80)),
                ('fechanac', models.DateTimeField()),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColorVehiculo',
            fields=[
                ('idcolor', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nomcolor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'color_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nomcomuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOp',
            fields=[
                ('iddetalleop', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.IntegerField()),
                ('precio', models.FloatField()),
                ('totallinea', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_op',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleServ',
            fields=[
                ('iddetallerserv', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cantidadprod', models.IntegerField()),
                ('costoprod', models.FloatField()),
                ('costototal', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_serv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleServot',
            fields=[
                ('iddetalleservot', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_serv', models.SmallIntegerField()),
                ('precioserv', models.FloatField()),
                ('totallineaserv', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_servot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('iddetallev', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidadventa', models.BigIntegerField()),
                ('precio', models.IntegerField()),
                ('totallinea', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoOt',
            fields=[
                ('idestadoot', models.IntegerField(primary_key=True, serialize=False)),
                ('nomestadoot', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'estado_ot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('idestadosol', models.IntegerField(primary_key=True, serialize=False)),
                ('descripestado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoraAgenda',
            fields=[
                ('idhora', models.IntegerField(primary_key=True, serialize=False)),
                ('rangohora', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'hora_agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngresoVehiculo',
            fields=[
                ('idingresovehi', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField()),
                ('motivo', models.CharField(max_length=500)),
                ('diagnostico', models.CharField(max_length=500)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ingreso_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('idmarca', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nommarca', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marca_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idmetodo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nommetodo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('idmodelo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nommodelo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'modelo_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('idop', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaop', models.DateTimeField()),
                ('montoneto', models.BigIntegerField()),
                ('montoiva', models.BigIntegerField()),
                ('montototal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('idot', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaot', models.DateTimeField()),
                ('presupuestoinicial', models.BigIntegerField()),
                ('costofinal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'orden_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nomproducto', models.CharField(max_length=60)),
                ('preciounitario', models.BigIntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rutproveedor', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('fono', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepcionOp',
            fields=[
                ('idrecepcionot', models.IntegerField(primary_key=True, serialize=False)),
                ('fecharecepcion', models.DateTimeField()),
                ('conformidad', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'recepcion_op',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nomservicio', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudDiag',
            fields=[
                ('idsolicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('fechasol', models.DateTimeField()),
                ('motivo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'solicitud_diag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_adquirido', models.IntegerField()),
                ('cant_venta', models.IntegerField()),
                ('cant_disponible', models.IntegerField()),
                ('stock_minimo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'stock_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TallerMecanico',
            fields=[
                ('idtaller', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ruttaller', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('fono1', models.BigIntegerField()),
                ('fono2', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=80)),
                ('fechacreacion', models.DateTimeField()),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'taller_mecanico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idtipodoc', models.IntegerField(primary_key=True, serialize=False)),
                ('nomdoc', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rutusuario', models.CharField(max_length=10)),
                ('nomusuario', models.CharField(max_length=60)),
                ('apepaterno', models.CharField(max_length=50)),
                ('apematerno', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('fono', models.BigIntegerField()),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(max_length=30)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateTimeField()),
                ('montoneto', models.BigIntegerField()),
                ('montooiva', models.BigIntegerField()),
                ('montototal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
