# Generated by Django 2.2 on 2019-05-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTallerGTM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePortal',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('runcliente', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=80)),
                ('apepaterno', models.CharField(max_length=80)),
                ('apematerno', models.CharField(max_length=80)),
                ('fechanac', models.DateTimeField()),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=25)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cliente_portal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteTaller',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('runcliente', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=80)),
                ('apepaterno', models.CharField(max_length=80)),
                ('apematerno', models.CharField(max_length=80)),
                ('fechanac', models.DateTimeField()),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=25)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cliente_taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleAgenda',
            fields=[
                ('iddetalleagenda', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleEspecialidad',
            fields=[
                ('iddetalleesp', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nomespecialidad', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.AutoField(primary_key=True, serialize=False)),
                ('nomregion', models.CharField(max_length=100)),
                ('numromano', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehiculoPortal',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('activo', models.CharField(max_length=1)),
                ('idcliente', models.IntegerField()),
                ('idcolor', models.IntegerField()),
                ('idmodelo', models.IntegerField()),
                ('idmarca', models.IntegerField()),
            ],
            options={
                'db_table': 'vehiculo_portal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehiculoTaller',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('activo', models.CharField(max_length=1)),
                ('idcliente', models.IntegerField()),
                ('idcolor', models.IntegerField()),
                ('idmodelo', models.IntegerField()),
                ('idmarca', models.IntegerField()),
            ],
            options={
                'db_table': 'vehiculo_taller',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
